-   client_id: 0
    final_search_space: &id004
        client_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            weight_decay:
                type: float
                min: 1.0e-06
                max: 0.001
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu:
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 30.133928571428573
-   client_id: 1
    final_search_space:
        client_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            weight_decay:
                type: float
                min: 1.0e-06
                max: 0.001
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu:
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 35.267857142857146
-   client_id: 2
    final_search_space:
        client_hps: &id001
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            weight_decay:
                type: float
                min: 1.0e-06
                max: 0.001
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps: &id002
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu: &id003
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
-   client_id: 3
    final_search_space:
        client_hps: *id001
        server_hps: *id002
        mu: *id003
-   client_id: 4
    final_search_space:
        client_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            weight_decay:
                type: float
                min: 1.0e-06
                max: 0.001
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu:
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.002
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2.0
                    batch_size: 64
                    dropout_rate: 0.2
                server:
                    learning_rate: 0.002
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 40.513392857142854
-   client_id: 5
    final_search_space:
        client_hps: *id001
        server_hps: *id002
        mu: *id003
-   client_id: 6
    final_search_space:
        client_hps: *id001
        server_hps: *id002
        mu: *id003
-   client_id: 7
    final_search_space:
        client_hps: *id001
        server_hps: *id002
        mu: *id003
-   client_id: 8
    final_search_space:
        client_hps: *id001
        server_hps: *id002
        mu: *id003
-   client_id: 9
    final_search_space: *id004
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.01
                    weight_decay: 1.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 3
                    batch_size: 128
                    dropout_rate: 0.5
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 26.5625
