-   client_id: 0
    final_search_space: &id003
        client_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            weight_decay:
                type: float
                min: 1.0e-06
                max: 0.001
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu:
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 52.49399038461539
        'Global Epoch: 1':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 61.02764423076923
-   client_id: 1
    final_search_space:
        client_hps:
            learning_rate:
                type: float
                min: 0.0005
                max: 0.0015
                initial: 0.001
            weight_decay:
                type: float
                min: 5.0e-05
                max: 0.0002
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu:
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 51.12179487179487
        'Global Epoch: 1':
            hps_suggested: &id001
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 60.66706730769231
        'Global Epoch: 2':
            hps_suggested: *id001
            final_test_accuracy: 62.57011217948718
-   client_id: 2
    final_search_space:
        client_hps: &id004
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            weight_decay:
                type: float
                min: 1.0e-06
                max: 0.001
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps: &id005
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu: &id006
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
-   client_id: 3
    final_search_space:
        client_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.0005
                initial: 0.001
            weight_decay:
                type: float
                min: 1.0e-06
                max: 5.0e-05
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu:
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
    original_hpo_report:
        'Global Epoch: 1':
            hps_suggested: &id002
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 63.571714743589745
        'Global Epoch: 2':
            hps_suggested: *id002
            final_test_accuracy: 70.24238782051282
-   client_id: 4
    final_search_space: *id003
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 47.546073717948715
        'Global Epoch: 2':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 63.7119391025641
-   client_id: 5
    final_search_space: *id003
    original_hpo_report:
        'Global Epoch: 1':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 58.15304487179487
        'Global Epoch: 2':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 59.8056891025641
-   client_id: 6
    final_search_space: *id003
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 58.35336538461539
        'Global Epoch: 2':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 62.15945512820513
-   client_id: 7
    final_search_space:
        client_hps: *id004
        server_hps: *id005
        mu: *id006
-   client_id: 8
    final_search_space: *id003
    original_hpo_report:
        'Global Epoch: 1':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 65.41466346153847
-   client_id: 9
    final_search_space:
        client_hps:
            learning_rate:
                type: float
                min: 0.0005
                max: 0.0015
                initial: 0.001
            weight_decay:
                type: float
                min: 5.0e-05
                max: 0.0002
                initial: 5.0e-05
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: CosineAnnealingLR
            local_epochs:
                type: int
                min: 1
                max: 3
                initial: 2
            batch_size:
                type: choice
                values:
                - 8
                - 16
                - 32
                - 64
                - 128
                initial: 64
            dropout_rate:
                type: float
                min: 0.0
                max: 0.5
                initial: 0.1
        server_hps:
            learning_rate:
                type: float
                min: 0.0001
                max: 0.01
                initial: 0.001
            momentum:
                type: float
                min: 0.8
                max: 0.99
                initial: 0.9
            optimizer:
                type: choice
                values:
                - AdamW
                - SGD
                - Adam
                initial: AdamW
            scheduler:
                type: choice
                values:
                - CosineAnnealingLR
                - StepLR
                - None
                initial: None
        mu:
            type: float
            min: 0.0
            max: 0.0
            initial: 0.0
    original_hpo_report:
        'Global Epoch: 0':
            hps_suggested:
                client:
                    learning_rate: 0.001
                    weight_decay: 5.0e-05
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: CosineAnnealingLR
                    local_epochs: 2
                    batch_size: 64
                    dropout_rate: 0.1
                server:
                    learning_rate: 0.001
                    momentum: 0.9
                    optimizer: AdamW
                    scheduler: None
                mu: 0.0
            final_test_accuracy: 59.32491987179487
